clone:
    lfs: true

image:
  name: dckr-reg.lockton.com.br/builderimage:main
  username: $REG_USER
  password: $REG_P

definitions:
  services:
    docker:
      memory: 3072

pipelines:
    pull-requests: # Apenas valida se o merge e a build vão funcionar.
        '**':
            - step:
                name: Build Test Only
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$BITBUCKET_COMMIT_SHORT --build-arg ENV=dev .
                services:
                    - docker
    branches:
        master:
            - step:
                name: Publish Development
                deployment: test
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "main")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=dev .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker service update --with-registry-auth --image dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG $PROJECT_NAME-development"
                services:
                    - docker
        staging:
            - step:
                name: Publish Staging
                deployment: staging
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "staging")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=homolog .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker service update --with-registry-auth --image dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG $PROJECT_NAME-staging"
                services:
                    - docker
    custom:
        publishproduction:
            - step:
                name: Publish Production
                deployment: production
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "production")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=prod .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker service update --with-registry-auth --image dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG $PROJECT_NAME"
                services:
                    - docker
        createdev:
            - step:
                name: Create Dev Container
                deployment: test
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "main")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=dev .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker service create -d --publish target=80,published=$PROJECT_PORT --log-driver=gelf --log-opt gelf-address=udp://logserver.lockton.com.br:12201 --log-opt tag=$PROJECT_NAME-development --with-registry-auth --name $PROJECT_NAME-development dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG"
                services:
                    - docker
        createstaging:
            - step:
                name: Create Staging Container
                deployment: staging
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "staging")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=homolog .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker service create -d --publish target=80,published=$PROJECT_PORT --log-driver=gelf --log-opt gelf-address=udp://logserver.lockton.com.br:12201 --log-opt tag=$PROJECT_NAME-staging --with-registry-auth --name $PROJECT_NAME-staging dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG"
                services:
                    - docker
        createproduction:
            - step:
                name: Create Production Container
                deployment: production
                runs-on: locktonbrasilrunner
                script:
                    - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
                    - sed -i 's|YYZ|'$BITBUCKET_COMMIT_SHORT'|g' Dockerfile
                    - IMAGE_TAG=$(/builderbin/gettag.sh "$BITBUCKET_BRANCH" "$BITBUCKET_COMMIT" "production")
                    - echo "$REG_P" | docker login dckr-reg.lockton.com.br --username $REG_USER --password-stdin
                    - docker build -t dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG --build-arg ENV=prod .
                    - docker push dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker service create -d --publish target=80,published=$PROJECT_PORT --log-driver=gelf --log-opt gelf-address=udp://logserver.lockton.com.br:12201 --log-opt tag=$PROJECT_NAME --with-registry-auth --name $PROJECT_NAME dckr-reg.lockton.com.br/$PROJECT_NAME:$IMAGE_TAG"
                services:
                    - docker
        zdockercommanddevelopment:
            - step:
                name: Check Services
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker
        zdockerlsdevelopment:
            - step:
                name: Check Services
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker exec -it  $PROJECT_NAME-development /bin/bash"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "ls"
                services:
                    - docker
        zdockercommandproduction:
            - step:
                name: Check Services
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker
        zdockercommandstaging:
            - step:
                name: Check Services
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker