clone:
    lfs: true

image:
  name: dckr-reg.lockton.com.br/builderimage:main
  username: $REG_USER
  password: $REG_P

definitions:
  services:
    docker:
      memory: 3072

pipelines:
    custom:
        registryImageList:
            - step:
                name: Registry Project List
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "curl -X GET -u $REG_USER:$REG_P https://dckr-reg.lockton.com.br/v2/_catalog"
                services:
                    - docker
        registryImageTagList:
            - step:
                name: Registry Project Tag List
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "curl -X GET -u $REG_USER:$REG_P https://dckr-reg.lockton.com.br/v2/$TARGET_PROJECT_NAME/tags/list"
                services:
                    - docker
        registryImageFullTagList:
            - step:
                name: Registry Full Tag List
                runs-on: locktonbrasilrunner
                script:
                    - apt-get install jq -y
                    - IMAGETAGLIST=$(ansible dockerswarm3dev -i /ansibledefs/hosts -a "curl -X GET -u $REG_USER:$REG_P https://dckr-reg.lockton.com.br/v2/_catalog" | jq '.repositories[]')
                    - echo $IMAGETAGLIST
                    - for i in 1 2 3 4 5; do echo $i; done
                services:
                    - docker
        dev1ServiceList:
            - step:
                name: Service List Development
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker service ls"
                services:
                    - docker
        dev2DiskSpace:
            - step:
                name: Disk Space Development
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "df -h"
                services:
                    - docker
        dev3SystemPrune:
            - step:
                name: System Prune Development
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker system prune -f"
                services:
                    - docker
        devZCustomCommand:
            - step:
                name: Custom Command Development
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm3dev -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker
        homolog1ServiceList:
            - step:
                name: Service List Staging
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker service ls"
                services:
                    - docker
        homolog1ServiceInstall:
            - step:
                name: Service List Staging
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "sudo apt-get install libcap2-bin"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``"
                services:
                    - docker
        homolog2DiskSpace:
            - step:
                name: Disk Space Staging
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "df -h"
                services:
                    - docker
        homolog3SystemPrune:
            - step:
                name: System Prune Staging
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker system prune -f"
                services:
                    - docker
        homologZCustomCommand:
            - step:
                name: Custom Command Staging
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm1hom -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker
        prod1ServiceList:
            - step:
                name: Service List Production
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker service ls"
                services:
                    - docker
        prod2DiskSpace:
            - step:
                name: Disk Space Production
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "df -h"
                services:
                    - docker
        prod3SystemPrune:
            - step:
                name: System Prune Production
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker system prune -f"
                services:
                    - docker
        prodZCustomCommand:
            - step:
                name: Custom Command Production
                runs-on: locktonbrasilrunner
                script:
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "docker login dckr-reg.lockton.com.br --username $REG_USER --password $REG_P"
                    - ansible dockerswarm2pro -i /ansibledefs/hosts -a "$EXEC_COMMAND"
                services:
                    - docker